name: Run Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.2', '8.3', '8.4', '8.5' ]
        laravel: [ '11.*', '12.*', '13.*' ]
        stability: [ prefer-stable ]
        exclude:
          # Laravel 11 officially supports PHP 8.2 - 8.4
          - laravel: '11.*'
            php: '8.5'

          # Laravel 13 strictly requires PHP 8.3+
          - laravel: '13.*'
            php: '8.2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      # - name: Run static analysis
      #   run: vendor/bin/phpstan analyse

      - name: Ensure code structure
        run: vendor/bin/pint --test

      - name: Run tests
        run: vendor/bin/pest